# POSTTEST 7
## Pengenalan Tensorflow

### Library

In [39]:
import tensorflow as tf

#### Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [40]:
random_tensor = tf.random.normal([5,5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.8782151 , -1.136544  , -0.21195087, -0.29506448, -0.56027335],
       [ 1.0904956 ,  1.5580066 ,  0.4530346 ,  0.18423583,  0.02407954],
       [ 0.51235056,  1.0819257 ,  0.04912369,  0.6809474 ,  1.1356817 ],
       [-0.80516595, -0.10328689,  2.2049477 , -0.5318309 ,  0.2630845 ],
       [-1.1128261 , -0.59706914,  1.9051647 , -0.4894348 ,  0.08562752]],
      dtype=float32)>

#### Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [41]:
list_prime =[[2,3,5,7,11],[13,17,19,23,29],[31,37,41,43,47],[53,59,61,67,71],[73,79,83,89,97]]
prime_tensor = tf.convert_to_tensor(list_prime,dtype=tf.float32)
print(prime_tensor)

tf.Tensor(
[[ 2.  3.  5.  7. 11.]
 [13. 17. 19. 23. 29.]
 [31. 37. 41. 43. 47.]
 [53. 59. 61. 67. 71.]
 [73. 79. 83. 89. 97.]], shape=(5, 5), dtype=float32)


#### Tampilkan dimensi dari kedua variable tersebut

In [42]:
print(random_tensor.shape)
print(prime_tensor.shape)

(5, 5)
(5, 5)


#### Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

#### Penjumlahan

In [43]:
print(tf.add(random_tensor,prime_tensor))

tf.Tensor(
[[ 0.12178493  1.863456    4.788049    6.7049356  10.439727  ]
 [14.090496   18.558006   19.453035   23.184237   29.02408   ]
 [31.51235    38.081924   41.04912    43.680946   48.13568   ]
 [52.194836   58.896713   63.20495    66.46817    71.263084  ]
 [71.88718    78.40293    84.90517    88.51057    97.085625  ]], shape=(5, 5), dtype=float32)


#### Pengurangan

In [44]:
print(tf.subtract(random_tensor,prime_tensor))

tf.Tensor(
[[ -3.878215   -4.136544   -5.211951   -7.2950644 -11.560273 ]
 [-11.909504  -15.441994  -18.546965  -22.815763  -28.97592  ]
 [-30.48765   -35.918076  -40.95088   -42.319054  -45.86432  ]
 [-53.805164  -59.103287  -58.79505   -67.53183   -70.736916 ]
 [-74.11282   -79.59707   -81.09483   -89.48943   -96.914375 ]], shape=(5, 5), dtype=float32)


#### Perkalian

In [45]:
print(tf.multiply(random_tensor,prime_tensor))

tf.Tensor(
[[ -3.7564301   -3.409632    -1.0597544   -2.0654514   -6.163007  ]
 [ 14.176443    26.486113     8.607657     4.237424     0.69830674]
 [ 15.882868    40.031254     2.0140712   29.280739    53.37704   ]
 [-42.673794    -6.0939264  134.50182    -35.63267     18.678999  ]
 [-81.236305   -47.16846    158.12868    -43.559696     8.305869  ]], shape=(5, 5), dtype=float32)


#### Pembagian

In [46]:
print(tf.divide(random_tensor,prime_tensor))

tf.Tensor(
[[-9.3910754e-01 -3.7884799e-01 -4.2390175e-02 -4.2152070e-02
  -5.0933942e-02]
 [ 8.3884276e-02  9.1647446e-02  2.3843927e-02  8.0102533e-03
   8.3032908e-04]
 [ 1.6527437e-02  2.9241236e-02  1.1981388e-03  1.5835987e-02
   2.4163442e-02]
 [-1.5191810e-02 -1.7506253e-03  3.6146685e-02 -7.9377750e-03
   3.7054154e-03]
 [-1.5244193e-02 -7.5578373e-03  2.2953792e-02 -5.4992675e-03
   8.8275794e-04]], shape=(5, 5), dtype=float32)


#### Logaritma

In [47]:
print(tf.math.log(random_tensor,prime_tensor))

tf.Tensor(
[[        nan         nan         nan         nan         nan]
 [ 0.08663225  0.4434072  -0.79178673 -1.6915387  -3.7263927 ]
 [-0.66874623  0.07874256 -3.013414   -0.38427016  0.12723312]
 [        nan         nan  0.7907038          nan -1.3352801 ]
 [        nan         nan  0.64456844         nan -2.4577487 ]], shape=(5, 5), dtype=float32)


#### Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [48]:
max_random_tensor_column = tf.argmax(random_tensor,axis=0)
max_random_tensor_row = tf.argmax(random_tensor,axis=1)
min_random_tensor_column = tf.argmin(random_tensor,axis=0)
min_random_tensor_row = tf.argmin(random_tensor,axis=1)
print("Nilai Maksimal dari variabel random tensor berdasar kolom adalah : \n",max_random_tensor_column.numpy())
print("Nilai Maksimal dari variabel random tensor berdasar baris adalah : \n",max_random_tensor_row.numpy())
print("Nilai Minimal dari variabel random tensor berdasar kolom adalah : \n",min_random_tensor_column.numpy())
print("Nilai Minimal dari variabel random tensor berdasar baris adalah : \n",min_random_tensor_row.numpy())

Nilai Maksimal dari variabel random tensor berdasar kolom adalah : 
 [1 1 3 2 2]
Nilai Maksimal dari variabel random tensor berdasar baris adalah : 
 [2 1 4 2 2]
Nilai Minimal dari variabel random tensor berdasar kolom adalah : 
 [0 0 0 3 0]
Nilai Minimal dari variabel random tensor berdasar baris adalah : 
 [0 4 2 0 0]


#### Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [53]:
concat_tensor_column = tf.concat([random_tensor,prime_tensor],axis=0)
concat_tensor_row = tf.concat([random_tensor,prime_tensor],axis=1)
print("Penggabungan Variabel Berdasar Kolom : \n",concat_tensor_column)
print("")
print("Penggabungan Variabel Berdasar Baris \n",concat_tensor_row)

Penggabungan Variabel Berdasar Kolom : 
 tf.Tensor(
[[-1.8782151e+00 -1.1365440e+00 -2.1195087e-01 -2.9506448e-01
  -5.6027335e-01]
 [ 1.0904956e+00  1.5580066e+00  4.5303461e-01  1.8423583e-01
   2.4079543e-02]
 [ 5.1235056e-01  1.0819257e+00  4.9123690e-02  6.8094742e-01
   1.1356817e+00]
 [-8.0516595e-01 -1.0328689e-01  2.2049477e+00 -5.3183091e-01
   2.6308450e-01]
 [-1.1128261e+00 -5.9706914e-01  1.9051647e+00 -4.8943481e-01
   8.5627519e-02]
 [ 2.0000000e+00  3.0000000e+00  5.0000000e+00  7.0000000e+00
   1.1000000e+01]
 [ 1.3000000e+01  1.7000000e+01  1.9000000e+01  2.3000000e+01
   2.9000000e+01]
 [ 3.1000000e+01  3.7000000e+01  4.1000000e+01  4.3000000e+01
   4.7000000e+01]
 [ 5.3000000e+01  5.9000000e+01  6.1000000e+01  6.7000000e+01
   7.1000000e+01]
 [ 7.3000000e+01  7.9000000e+01  8.3000000e+01  8.9000000e+01
   9.7000000e+01]], shape=(10, 5), dtype=float32)

Penggabungan Variabel Berdasar Baris 
 tf.Tensor(
[[-1.8782151e+00 -1.1365440e+00 -2.1195087e-01 -2.9506448e-01
  -

#### Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [60]:
sorted_tensor_random = tf.sort(random_tensor,direction="DESCENDING")
sorted_index_random = tf.argsort(random_tensor,direction="DESCENDING")
sorted_tensor_prime =  tf.sort(prime_tensor,direction="DESCENDING")
sorted_index_prime = tf.argsort(prime_tensor,direction="DESCENDING")
print("Hasil Sorting dari variabel random tensor berdasar tensor adalah\n\n",sorted_tensor_random,"\n")
print("Hasil Sorting dari variabel random tensor berdasar index adalah\n\n",sorted_index_random,"\n")
print("Hasil Sorting dari variabel prime tensor berdasar tensor adalah\n\n",sorted_tensor_prime,"\n")
print("Hasil Sorting dari variabel prime tensor berdasar index adalah\n\n",sorted_index_prime,"\n")

Hasil Sorting dari variabel random tensor berdasar tensor adalah

 tf.Tensor(
[[-0.21195087 -0.29506448 -0.56027335 -1.136544   -1.8782151 ]
 [ 1.5580066   1.0904956   0.4530346   0.18423583  0.02407954]
 [ 1.1356817   1.0819257   0.6809474   0.51235056  0.04912369]
 [ 2.2049477   0.2630845  -0.10328689 -0.5318309  -0.80516595]
 [ 1.9051647   0.08562752 -0.4894348  -0.59706914 -1.1128261 ]], shape=(5, 5), dtype=float32) 

Hasil Sorting dari variabel random tensor berdasar index adalah

 tf.Tensor(
[[2 3 4 1 0]
 [1 0 2 3 4]
 [4 1 3 0 2]
 [2 4 1 3 0]
 [2 4 3 1 0]], shape=(5, 5), dtype=int32) 

Hasil Sorting dari variabel prime tensor berdasar tensor adalah

 tf.Tensor(
[[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32) 

Hasil Sorting dari variabel prime tensor berdasar index adalah

 tf.Tensor(
[[4 3 2 1 0]
 [4 3 2 1 0]
 [4 3 2 1 0]
 [4 3 2 1 0]
 [4 3 2 1 0]], shape=(5, 5), dtype=int32) 

